### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by elronzo** [markbolhuis/libeizo#1]
Please provide two sentences on how to compile this. I am not familiar with meson so I do not have a clue yet.

**Comment by markbolhuis** [comment]
To build:
```
meson setup build
meson compile -C build
```
Then to run:
```
./build/eizoctl
```
Meson has excellent [documentation](https://mesonbuild.com/Running-Meson.html).

**Comment by elronzo** [comment]
lol... I guessed everything right except the "-C" param which I typed lowercase. Thank you!
